### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by jaytmiller**
Added testing for .travis: pytest, flake8, black, bandit.
Added high level checks for process.py which run 4 ipppssoots and verifies that the products defined in the tests are produced and have lengths withing 10% of the test outputs.
Revised installation scripts to support a complete conda install on Linux or OS-X as well as components: "stable" or "latest" conda package lists for the fundamental CAL code,  fitscut, and CALDP.
Revised Dockerfile to support parameterized base image from new location at stsci/hst-pipeline with tags "stable" or "latest".
Fixed caldp-process for use with AWS Lambda.
Fixed create_preview handling of "none" output.
Fixed black errors.
Removed tox.ini not useful (even with tox-conda) for conda package list installs.

Unfortunately I can't rebase this into a single commit due to tons of rebase conflicts I don't fully understand.   There were some conflicts caused by colliding README edits which I resolved.

### CODE REVIEW

**Comment by jaytmiller** [comment]
Look here: https://github.com/jaytmiller/caldp/runs/1005099644 to see what Travis now does in my account and I believe spacetelescope as well.

**Comment by bhayden53** [comment]
The PR message says it checks 4 ipppssoots but the test looks like it's only testing one, which is I think what you told me in standup. Is 1 ipppssoot the intended behavior for now?

**Comment by jaytmiller** [comment]
The Docker build only tests one ipppssoot.   The functional tests should be testing 4 or there is something wrong.   I wanted them to check all instruments but they're currently only checking 3.   These are tripwire tests,  we need to use something like nightlies to stay on top of regressions and different modes of process.py... possibly with some integration with AWS to actually test the lambda operation.   Travis does support cron jobs but I think running too long is probably abuse  of the service.   And AWS cronjob would probably be perfect,   that could use CRDS without hitting the server and test S3.

**Comment by bhayden53** [comment]
Ok, the travis logs for the functional tests won't have the details of those ipppssoots (i.e. actual cal code stdout, like the other test does), so I couldn't tell that multiple ipppssoots were running in there.

**Comment by bhayden53** [comment]
`.eggs` should be in gitignore I think, if I run `tox` a README gets changed in there and git wants me to re-commit the file.

**Comment by bhayden53** [comment]
I built a new image and ran `caldp-docker-run-pipeline`  with local inputs and outputs, and it looks like the previews code is being run on the wrong directory. Already talked with Todd privately and I think a patch is incoming, just writing here for artifact purposes.

**Comment by bhayden53** [comment]
Todd let me know a new, cleaner PR is being worked on to cover this work, so closing without merging.

**Pull request closed without merging**
